[package]
authors = ['Phala Network']
edition = '2018'
name = 'phala-pallets'
version = "3.3.0"
license = "Apache 2.0"
homepage = "https://phala.network/"
repository = "https://github.com/Phala-Network/phala-blockchain"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.2", default-features = false, features = ["derive", "max-encoded-len"] }
primitive-types = { version = "0.10", default-features = false, features = ["codec", "byteorder"] }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12", default-features = false }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12", default-features = false }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12", default-features = false, optional = true }
log = { version = "0.4.14", default-features = false }

pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12", default-features = false }

phala-types = { path = "../../crates/phala-types", default-features = false }
chrono = { version = "0.4", default-features = false }
untrusted = { version = "0.7" }
base64 = { version = "0.11", default-features = false, features = ["alloc"] }
hex = { version = "0.4", default-features = false }
serde_json = { version = "1.0.41", default-features = false, features = ["alloc"] }
fixed = { version = "1.9", default-features = false }
fixed-macro = { git = "https://github.com/kvinwang/fixed-macro.git", version = "1.1", default-features = false }
fixed-sqrt = { version = "0.2", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
webpki = { version = "0.22", default-features = false, features = ["alloc"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
webpki_wasm = { package = "webpki", path = "../../vendor/webpki", default-features = false, features = ["alloc"] }

[dev-dependencies]
frame-support-test = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
assert_matches = "1.4.0"
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.12" }
hex-literal = "0.3.1"
libsecp256k1 = { version = "0.3.2", default-features = false }
rand = "0.7.3"

[features]
default = ['std']
std = [
    "codec/std",
    "sp-runtime/std",
    "frame-support/std",
    "frame-system/std",
    "sp-io/std",
    "sp-std/std",
    "sp-core/full_crypto",
    "frame-benchmarking/std",
    "pallet-balances/std",
    "log/std",
    "phala-types/enable_serde",
]
runtime-benchmarks = [
    "frame-benchmarking"
]
try-runtime = ["frame-support/try-runtime"]
native = [
    "sp-application-crypto/full_crypto",
]
