[package]
name = "cumulus-client-consensus-common"
description = "Cumulus specific common consensus implementations"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
async-trait = "0.1.68"
codec = { package = "parity-scale-codec", version = "3.0.0", features = [ "derive" ] }
dyn-clone = "1.0.11"
futures = "0.3.28"
log = "0.4.17"
tracing = "0.1.37"

# Substrate
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }

# Polkadot
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.41" }

# Cumulus
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.41" }
cumulus-relay-chain-interface = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.41" }
cumulus-client-pov-recovery = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.41" }
schnellru = "0.2.1"

[dev-dependencies]
futures-timer = "3.0.2"

# Substrate
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }

# Cumulus
cumulus-test-client = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.41" }
