[package]
name = "polkadot-node-core-dispute-coordinator"
version = "0.9.41"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
futures = "0.3.21"
gum = { package = "tracing-gum", git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.41" }
parity-scale-codec = "3.3.0"
kvdb = "0.13.0"
thiserror = "1.0.31"
lru = "0.9.0"
fatality = "0.0.6"

polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.41" }
polkadot-node-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.41" }
polkadot-node-subsystem = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.41" }
polkadot-node-subsystem-util = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.41" }

sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }


[dev-dependencies]
kvdb-memorydb = "0.13.0"
polkadot-node-subsystem-test-helpers = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.41" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
assert_matches = "1.4.0"
test-helpers = { package = "polkadot-primitives-test-helpers", git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.41" }
futures-timer = "3.0.2"
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.41" }

[features]
# If not enabled, the dispute coordinator will do nothing.
disputes = []
